### ISSUE TITLE
Image generator!!!

### ISSUE THREAD

**Issue by sekkurocode** [heyitsalina/big_data_image_recommender#18]
Add images to a new table in the image_metadata.db

**Comment by heyitsalina** [comment]
AMAZING

**Comment by sekkurocode** [comment]
The image_metadata.db file is already too large for github to take it, so what are we supposed to do? I've loaded a thousand images onto it, but they are not compressed at all. Surely that's not the point of this exercise?!?!

**Comment by sekkurocode** [comment]
Okay figured shit out. The .db file is dangerous asf hahahaha
